// ---------------------------------------------------------------------------
// RSS Directory Submission URLs
// Top active RSS directories and aggregators for submitting your feed.
// Feed URL: https://vacationdeals.to/feed.xml
// ---------------------------------------------------------------------------

export const RSS_DIRECTORIES: { name: string; submitUrl: string }[] = [
  // --- Tier 1: Major aggregators & readers ---
  { name: "Feedly", submitUrl: "https://feedly.com/i/discover/sources/search/feed/https://vacationdeals.to/feed.xml" },
  { name: "Feedspot", submitUrl: "https://www.feedspot.com/submit-rss-feed/" },
  { name: "Inoreader", submitUrl: "https://www.inoreader.com/" },
  { name: "NewsBlur", submitUrl: "https://newsblur.com/" },
  { name: "The Old Reader", submitUrl: "https://theoldreader.com/" },
  { name: "Feedbin", submitUrl: "https://feedbin.com/" },
  { name: "Flipboard", submitUrl: "https://share.flipboard.com/" },
  { name: "Google News", submitUrl: "https://publishercenter.google.com/" },
  { name: "Apple News", submitUrl: "https://www.icloud.com/publish/" },
  { name: "Microsoft Start", submitUrl: "https://partner.microsoft.com/en-us/dashboard/microsoftstart" },

  // --- Tier 2: Blog directories & aggregators ---
  { name: "Blogarama", submitUrl: "https://www.blogarama.com/submit-blog/" },
  { name: "Blog Directory", submitUrl: "https://www.blog-directory.org/submit.php" },
  { name: "Bloglovin", submitUrl: "https://www.bloglovin.com/blogs/claim" },
  { name: "AllTop", submitUrl: "https://alltop.com/submission" },
  { name: "Blog Starter", submitUrl: "https://www.theblogstarter.com/submit-blog/" },
  { name: "BlogHub", submitUrl: "https://bloghub.com/submit" },
  { name: "BlogSearchEngine", submitUrl: "https://www.blogsearchengine.org/submit.html" },
  { name: "GlobeOfBlogs", submitUrl: "https://www.globeofblogs.com/submit_blog.php" },
  { name: "Bloggernity", submitUrl: "https://www.bloggernity.com/submit.php" },
  { name: "BlogCatalog", submitUrl: "https://www.blogcatalog.com/" },
  { name: "Blog Engage", submitUrl: "https://blogengage.com/" },
  { name: "OnTopList", submitUrl: "https://www.ontoplist.com/submit-blog/" },
  { name: "Blog Flux", submitUrl: "https://www.blogflux.com/submitblog.php" },
  { name: "Blog Listing", submitUrl: "https://bloglisting.net/submit.php" },
  { name: "Blog Top Sites", submitUrl: "https://www.blogtopsites.com/register" },
  { name: "Best of the Web Blog", submitUrl: "https://botw.org/submit/" },
  { name: "EatonWeb Blog Directory", submitUrl: "https://blog.eaton.com/portal/" },
  { name: "9Rules", submitUrl: "https://9rules.com/submit/" },
  { name: "Qwant", submitUrl: "https://help.qwant.com/en/submit/" },

  // --- Tier 3: RSS-specific directories ---
  { name: "RSS Micro", submitUrl: "https://www.rssmicro.com/submitrss.php" },
  { name: "Feed Shark", submitUrl: "http://feedshark.brainbliss.com/" },
  { name: "RSS Top 55", submitUrl: "https://www.rsstop55.com/submit-rss-feed" },
  { name: "Feedage", submitUrl: "https://www.feedage.com/submit-rss-feed/" },
  { name: "Feed Burner Directory", submitUrl: "https://feedburner.google.com/" },
  { name: "FeedPlex", submitUrl: "https://www.feedplex.com/submit" },
  { name: "FeedCatch", submitUrl: "https://www.feedcatch.com/submit-rss-feed/" },
  { name: "RSS-Verzeichnis", submitUrl: "https://www.rss-verzeichnis.de/submit.php" },
  { name: "Syndic8", submitUrl: "http://www.syndic8.com/suggest.php" },
  { name: "Plazoo", submitUrl: "https://www.plazoo.com/en/addfeed.asp" },
  { name: "RSSOwl", submitUrl: "https://www.rssowl.org/" },
  { name: "FeedMyInbox", submitUrl: "https://www.feedmyinbox.com/" },
  { name: "R-bloggers (niche)", submitUrl: "https://www.r-bloggers.com/add-your-blog/" },
  { name: "FeedSpool", submitUrl: "https://www.feedspool.com/submit.php" },
  { name: "ReadAbility", submitUrl: "https://www.readability.com/" },
  { name: "Newsgator / NetNewsWire", submitUrl: "https://netnewswire.com/" },
  { name: "FeedValidator (verify)", submitUrl: "https://validator.w3.org/feed/" },

  // --- Tier 4: Travel-specific & niche directories ---
  { name: "Travel Blog Directory", submitUrl: "https://www.travelblogdirectory.com/submit/" },
  { name: "Travel Bloggers Buzz", submitUrl: "https://travelbloggersbuzz.com/submit-blog/" },
  { name: "Travel Massive", submitUrl: "https://travelmassive.com/join" },
  { name: "Trip Advisor Forum", submitUrl: "https://www.tripadvisor.com/ForumHome" },
  { name: "Nomadic Matt Blog Directory", submitUrl: "https://www.nomadicmatt.com/travel-blogs/" },
  { name: "Matador Network", submitUrl: "https://matadornetwork.com/content-creator-community/" },
  { name: "Wanderlust Travel Directory", submitUrl: "https://www.wanderlust.co.uk/" },
  { name: "TravBuddy", submitUrl: "https://www.travbuddy.com/" },
  { name: "BootsnAll", submitUrl: "https://www.bootsnall.com/" },
  { name: "GoAbroad", submitUrl: "https://www.goabroad.com/" },

  // --- Tier 5: Social bookmarking & content platforms ---
  { name: "Mix.com (StumbleUpon)", submitUrl: "https://mix.com/" },
  { name: "Pocket", submitUrl: "https://getpocket.com/" },
  { name: "Refind", submitUrl: "https://refind.com/" },
  { name: "Raindrop.io", submitUrl: "https://raindrop.io/" },
  { name: "Digg", submitUrl: "https://digg.com/submit" },
  { name: "Slashdot", submitUrl: "https://slashdot.org/submit" },
  { name: "DZone", submitUrl: "https://dzone.com/links" },
  { name: "BizSugar", submitUrl: "https://www.bizsugar.com/" },
  { name: "Scoop.it", submitUrl: "https://www.scoop.it/" },
  { name: "Paper.li", submitUrl: "https://paper.li/" },
  { name: "Medium (import)", submitUrl: "https://medium.com/p/import" },
  { name: "Tumblr (reblog)", submitUrl: "https://www.tumblr.com/" },
  { name: "Reddit (niche subs)", submitUrl: "https://www.reddit.com/submit" },

  // --- Tier 6: Search engine & webmaster tools ---
  { name: "Google Search Console", submitUrl: "https://search.google.com/search-console" },
  { name: "Bing Webmaster Tools", submitUrl: "https://www.bing.com/webmasters/" },
  { name: "Yandex Webmaster", submitUrl: "https://webmaster.yandex.com/" },
  { name: "IndexNow (Bing/Yandex)", submitUrl: "https://www.indexnow.org/submiturl" },
  { name: "Baidu Webmaster Tools", submitUrl: "https://ziyuan.baidu.com/" },
  { name: "Naver Webmaster Tools", submitUrl: "https://searchadvisor.naver.com/" },
  { name: "Seznam Webmaster", submitUrl: "https://search.seznam.cz/submit" },

  // --- Tier 7: Podcast & multimedia directories (if applicable) ---
  { name: "Spotify for Creators", submitUrl: "https://podcasters.spotify.com/" },
  { name: "Listen Notes", submitUrl: "https://www.listennotes.com/submit/" },
  { name: "Podcast Index", submitUrl: "https://podcastindex.org/add" },

  // --- Tier 8: Link building & web directories ---
  { name: "DMOZ (Curlie)", submitUrl: "https://curlie.org/docs/en/add.html" },
  { name: "Jasmine Directory", submitUrl: "https://www.jasminedirectory.com/submit.php" },
  { name: "Spoke.com", submitUrl: "https://www.spoke.com/" },
  { name: "Blogging Fusion", submitUrl: "https://www.bloggingfusion.com/submit-blog/" },
  { name: "Blog Directory UK", submitUrl: "https://www.blogdirectory.co.uk/submit.php" },
  { name: "Best Blog Directory", submitUrl: "https://bestblogdirectory.com/submit-blog/" },
  { name: "Blog Directory Online", submitUrl: "https://www.blogdirectoryonline.com/submit-blog/" },
  { name: "Add Blog", submitUrl: "https://www.addblog.org/submit.php" },
  { name: "Blog Village", submitUrl: "https://blogvillage.org/submit" },
  { name: "Directory Critic", submitUrl: "https://www.directorycritic.com/" },
  { name: "Blog Street", submitUrl: "https://www.blogstreet.com/suggest.html" },
  { name: "Blog Universe", submitUrl: "https://www.bloguniverse.com/submit/" },
  { name: "Blog Interact", submitUrl: "https://www.bloginteract.com/submit-blog/" },
  { name: "Blog Trainer", submitUrl: "https://blogtrainer.com/submit/" },
  { name: "Blog-Starter Directory", submitUrl: "https://www.blog-starter.com/blog-directory/" },
  { name: "Blogs Directory", submitUrl: "https://www.blogs-directory.com/submit.php" },
  { name: "Top Blog Area", submitUrl: "https://topblogarea.com/submit-blog/" },
  { name: "Top Blogs", submitUrl: "https://www.topblogs.com/submit" },
  { name: "Blog Rank", submitUrl: "https://www.blogrankers.com/submit-blog/" },
  { name: "A1 Web Directory", submitUrl: "https://www.a1webdirectory.org/submit.php" },
  { name: "SoMuch Directory", submitUrl: "https://www.somuch.com/submit-links/" },
  { name: "Starter Blog Directory", submitUrl: "https://www.starterblogdirectory.com/submit/" },
  { name: "Blog Dash", submitUrl: "https://www.blogdash.com/join/" },
  { name: "BlokBe", submitUrl: "https://blokbe.com/submit" },
  { name: "Blog Toplist", submitUrl: "https://www.blogtoplist.com/submit-blog/" },
  { name: "Blog Directory Submit", submitUrl: "https://blogdirectorysubmit.com/" },
  { name: "Alive Directory", submitUrl: "https://www.alivedirectory.com/submit.php" },
  { name: "Pegasus Directory", submitUrl: "https://www.pegasusdirectory.com/submit.php" },
  { name: "Family Friendly Sites", submitUrl: "https://www.familyfriendlysites.com/submit.php" },
  { name: "Directory World", submitUrl: "https://www.directoryworld.net/submit.php" },
  { name: "One Mission Directory", submitUrl: "https://www.onemission.com/submit/" },
];
